IMAGE_NAME = "bento/ubuntu-16.04"
N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.boot_timeout = 1000
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "<insert_first_initial_last_name_as_one_string_lowercases>-k8s-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.<insert_IP_string_not_in_use>.10"
        master.vm.hostname = "<insert_first_initial_last_name_as_one_string_lowercases>-k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.<insert_IP_string_not_in_use>.10",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "<insert_first_initial_last_name_as_one_string_lowercases>-node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.<insert_IP_string_not_in_use>.#{i + 10}"
            node.vm.hostname = "<insert_first_initial_last_name_as_one_string_lowercases>-node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.<insert_IP_string_not_in_use>.#{i + 10}",
                }
            end
        end
    end
end
