apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx-master
spec:
  containers:
  - name: nginx-master
    image: nginx
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
