apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis-container
    image: redis
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
